name: CI/CD for Nginx App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-nginx-app .

    - name: Push Docker image to Minikube
      run: |
        echo "Pushing Docker image to Minikube..."
        minikube image load my-nginx-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
